<a href="https://colab.research.google.com/github/Aman-Kumar342/langchain/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# numpy is a fundamentl libaray for scientific computing in python . it

In [1]:
import numpy as np

# create  array using numpy
# create a 1d array
arr1=np.array([1,2,3,4,5,])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [3]:
arr2=np.array([1,2,3,4,5,6])
arr2.reshape(1,6)

array([[1, 2, 3, 4, 5, 6]])

In [4]:
arr3=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr2)
print(arr2.shape)

[1 2 3 4 5 6]
(6,)
